spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis-plus-cascade?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver


