@startuml
actor 加盟商
加盟商 -> 门店宝前端: 提交订单
门店宝前端 -> 门店宝前端: 请求参数搜集
门店宝前端 -> 门店宝: 提交订单请求
门店宝 -> 报货中心: 提交订单请求
报货中心 -> 报货中心: 必填参数校验
报货中心 -> 报货中心: 校验门店是否被禁用
报货中心 -> 报货中心: 校验订单限购物料……
报货中心 -> 商品中心: 查询物料数据
loop 根据商品中心物料数据循环判断购物车订单行的价格
opt 价格不一致
报货中心 -> 报货中心: 加入订单行的价格变动标记、新价格
end
end
opt 价格不一致的列表不为空
报货中心 --> 门店宝: 返回价格不一致错误码，返回价格不一致信息
门店宝 --> 门店宝前端: 返回价格不一致错误码，返回价格不一致信息
门店宝前端 --> 加盟商: 二次确认价格变动或返回购物车
end
报货中心 -> 报货中心: 拆单
报货中心 -> 报货中心: 创建订单、订单行
报货中心 --> 门店宝: 下单成功
门店宝 --> 门店宝前端: 下单成功
门店宝前端 --> 加盟商: 下单成功
@enduml