@startuml
'https://plantuml.com/sequence-diagram

actor 店长
店长 -> 门店生产: 发起盘点
门店生产 -> 门店生产: 获取对应盘点模板分类数据
门店生产 -> 订单分析: 获取门店最近90天报货物料数据(以应收单审核时间为查询维度 理论和实际出库时间差1天)
门店生产 -> 门店生产: 搜集门店最近90天报货物料编码集
门店生产 -> 商品中心: 根据金蝶编码集查询商品中心 (一个编码对应多个商品问题如何解决)
门店生产 -> 门店生产: 如果一个金蝶编码存在多个商品 根据商品列表查询该门店可以报货哪个商品 如有取之 如无取第一个
门店生产 -> 门店生产: 商品在分类内 且鲜果<=15天 非鲜果<=90天 放入待盘点商品集
门店生产 -> 门店生产: 组装待盘点商品集
门店生产 -> 门店生产DB: 持久化盘点单及明细
门店生产 --> 店长: 展示待盘点商品数据
@enduml