@startuml

actor xxj_job
xxj_job -> 报货中心:发起定时报货分配请求
报货中心 -> DB: 查询共享库存配置表
DB --> 报货中心: 返回结果
报货中心 -> 报货中心: 按调入仓、物料+调出仓、物料纬度作为查询订单行数据的条件
报货中心 -> DB: 按条件查询出属于共享库存分配逻辑的订单、订单行
DB --> 报货中心: 返回结果
报货中心 -> 报货中心: 根据报货订单搜集门店信息
报货中心 -> 商品中心: 查询替代物料信息
报货中心 -> 商品中心: 创建每个物料报的门店数据集（用于计算销售占比）
报货中心 -> 门店看板: 按调入仓、调出仓为一组 获取门店过去7天的销售流水
报货中心 -> 报货中心: 按调入仓、调出仓为一组 排序门店的销售流水
报货中心 -> 报货中心: 按调入仓、调出仓为一组 计算门店销售占比
报货中心 -> 金蝶: 按调入仓、调出仓为一组 查询调出仓对应的库存
报货中心 -> 报货中心: 按调入仓、调出仓为一组 计算每个门店配置物料的最大报货量
报货中心 -> 报货中心: 一次分配
报货中心 -> 报货中心: 二次分配
报货中心 -> RDS:按<仓id+日期, 共享库存断货分配后的订单行结果>暂存共享分配结果 3天过期时间
报货中心 -> 报货中心: 走老的断货重分配逻辑 并剔除共享库存的订单行
报货中心 -> 报货中心: 合并共享、非共享断货重分配结果
报货中心 -> 金蝶: 推送金蝶
@enduml