@startuml
actor 加盟商
加盟商 -> 门店宝前端: 打开购物车
门店宝前端 -> 门店宝前端: 请求参数搜集
门店宝前端 -> 门店宝: 查询购物车数据
门店宝 -> 报货中心: 查询购物车数据
报货中心 -> DB: 根据门店查询购物车数据
报货中心 -> 报货中心: 搜集物料列表
报货中心 -> 商品中心: 查询物料数据
loop 根据商品中心物料数据循环判断购物车订单行的价格
opt 价格不一致
报货中心 -> 报货中心: 设置购物车订单行的价格变动标记、新价格
end
end
报货中心 --> 门店宝:返回购物车信息
门店宝 --> 门店宝前端:返回购物车信息
门店宝前端 --> 加盟商:页面渲染购物车信息
@enduml