@startuml
'https://plantuml.com/sequence-diagram

actor xxj_job
xxj_job -> 报货中心:发起定时报货分配请求
报货中心 -> nacos: 获取需要断货重分配的仓库列表
报货中心 -> 报货中心: 按仓纬度多线程并发分配
报货中心 -> 报货中心: 查询出次日需要配送的销售订单（排除预售、宣传物料、首批）
报货中心 -> 报货中心: 根据报货订单搜集门店信息
报货中心 -> 报货中心: 获取订单行
报货中心 -> 商品中心: 查询替代物料信息
报货中心 -> 商品中心: 创建每个物料报的门店数据集（用于计算销售占比）
报货中心 -> 门店看板: 获取门店过去7天的销售流水
报货中心 -> 报货中心: 排序门店、流水
报货中心 -> 报货中心: 计算销售占比
报货中心 -> 金蝶: 查询品（报货物料）仓（报货仓）对应的库存
报货中心 -> 报货中心: 计算最大报货量
报货中心 -> 报货中心: 一次分配
报货中心 -> 报货中心: 二次分配
报货中心 -> 金蝶:推送金蝶
@enduml