@startuml
actor 司机
司机 -> TMS: 扫码提交相关信息
TMS -> 报货中心: 调用回传差异信息接口
报货中心 -> redis: 根据金蝶单号加分布式锁
opt 加锁失败
报货中心 --> TMS: 异常请重试
end
报货中心 -> 报货中心: 必填参数校验
报货中心 -> 报货中心: 金蝶订单唯一性校验
报货中心 -> 金蝶: 根据金蝶单号查询金蝶单据信息
opt 金蝶单不存在
报货中心 --> TMS: 异常请重试
end
报货中心 -> 报货中心: 金蝶单据数据校验
报货中心 -> 店铺中心: 根据金蝶组织机构查询仓库信息
报货中心 -> 店铺中心: 查询店铺信息
报货中心 -> 报货中心: 组装差异单数据
报货中心 -> DB: 插入差异单据
opt 差异单据差异金额等于0
报货中心 -> redis: 处理完成分布式解锁
报货中心 --> TMS: 回传成功
end
opt 差异单据差异金额大于订单金额的40%
报货中心 -> redis: 处理完成分布式解锁
报货中心 --> 钉钉告警: 异常单据，流程结束
end
报货中心 -> 报货中心: 组装差异单推金蝶数据
报货中心 -> DB: 插入差异单据推金蝶数据(应收单)
报货中心 -> redis: 处理完成分布式解锁
报货中心 --> TMS: 回传成功

@enduml