@startuml
actor 产品运营
产品运营 -> 古茗后台: 物料修改
古茗后台 -> newton_admin: 提交物料修改请求
newton_admin -> newton_admin: 必填参数校验
newton_admin -> 商品中心: 修改物料
商品中心 -> 商品中心: 必填参数校验
商品中心 -> 商品中心: 根据id删除商品、规格信息数据
商品中心 -> 商品中心: 数据分类组装
商品中心 -> 商品中心: 数据新增
商品中心 --> newton_admin: 修改成功
newton_admin --> 古茗后台: 修改成功
古茗后台 --> 产品运营: 修改成功
@enduml