@startuml
actor 客服人员
客服人员 -> 简道云: 报损单审批通过
简道云 -> 八爪鱼: 报损单审批通过
八爪鱼 -> 八爪鱼: 获取报损单审批通过的数据
八爪鱼 -> 八爪鱼: 组装报损单创建请求入参
八爪鱼 -> 报货中心: 创建报损单
报货中心 -> redis: 尝试按报损单号加分布式锁
redis --> 报货中心: 返回加锁结果
opt 加锁失败
报货中心 --> 八爪鱼: 重复请求, 请稍后再试!
else 加锁成功
报货中心 -> 报货中心: 按报损单单号查询报损单
end
opt 报损单已存在
报货中心 --> 八爪鱼: 创建报损单成功
else 报损单不存在
报货中心 -> 报货中心: 组装报损单创建入参
end
opt 一致性事物
报货中心 -> 订单中心: 创建报损单
订单中心 --> 报货中心: 返回创建结果
opt 创建报损单失败
报货中心 --> 八爪鱼: 创建报损单失败, 订单中心保存异常, 请重试!
else 创建报损单成功
报货中心 -> 报货中心: 生成待推送金蝶的报损应收单推送任务
end
报货中心 -> DB: 插入待推送金蝶的报损应收单推送任务
DB --> 报货中心: 返回插入结果
opt 插入失败
报货中心 -> 订单中心: 删除报损单
报货中心 --> 八爪鱼: 创建报损单失败, 订单保存异常, 请重试!
end
end
报货中心 --> 八爪鱼: 创建报损单成功
八爪鱼 --> 简道云: 创建报损单成功
简道云 --> 客服人员: 处理成功
@enduml