@startuml
'https://plantuml.com/sequence-diagram

actor 门店生产
门店生产 -> RocketMQ: 订阅成本分析消息
门店生产 -> RocketMQ: 消费成本分析消息
门店生产 -> 门店宝: 查询灰度店铺配置
opt 灰度店铺配置为空
门店生产 -> RocketMQ: 消息提交
end
opt 消息的门店不在灰度门店内
门店生产 -> RocketMQ: 消息提交
end
门店生产 -> 策略配置中心: 分页查询灰度半成品配置
opt 灰度半成品配置为空
    门店生产 -> RocketMQ: 消息提交
end
opt 支付时间<今天凌晨5点
门店生产 -> RocketMQ: 消息提交
end
loop 按消息的半成品列表循环
opt 消息的半成品不在灰度半成品内
门店生产 -> 门店生产: continue;
end
门店生产 -> 门店生产: 计算使用变更量 支付+ 取消支付-
门店生产 -> Redis: 按照订单+半成品+支付状态加锁 超时时间为1天
opt 加锁失败
门店生产 -> 门店生产: continue;
end
门店生产 -> Redis: 获取支付时间分钟级别的店铺+半成品使用量数据
门店生产 -> 门店生产: 计算需变更使用量数据
门店生产 -> Redis: 更新支付时间分钟级别的店铺+半成品使用量数据
门店生产 -> 门店生产: 组装门店半成品使用量变更消息
end
门店生产 -> 策略配置中心: 查询门店高峰期配置
opt 高峰期配置为空或当前时间不在高峰期范围内
门店生产 -> RocketMQ: 消息提交
end
门店生产 -> RocketMQ: 发送门店半成品使用量变更消息
门店生产 -> RocketMQ: 消息提交
@enduml