@startuml
'https://plantuml.com/sequence-diagram

actor xxl_job
xxl_job -> 门店生产: 触发高峰期店铺断货提醒逻辑
门店生产 -> 门店宝: 查询灰度店铺配置
opt 灰度店铺配置为空
门店生产 -> xxl_job: end
end
门店生产 -> 策略配置中心: 分页查询全部高峰期配置
opt 高峰期配置为空
    门店生产 -> 门店生产: end;
end
门店生产 -> 门店生产: 组装高峰期配置Map<shopCode, Config>
loop 按灰度店铺循环
    opt 获取店铺对应高峰期配置为空
    门店生产 -> 门店生产: continue;
    end
    opt 当前时间 > 高峰期前一小时
    门店生产 -> 门店生产: continue;
    end
    门店生产 -> 效期系统: 按店铺+半成品编码列表纬度 查询全店最近一次生产数据
    效期系统 --> 门店生产: 返回最近一次半成品生产量数据集
        loop 按最近一次生产数据集循环
        门店生产 -> 数仓: 根据半成品查询从生产时间到高峰期开始时间前一小时的半成品使用量
        数仓 --> 门店生产: 返回使用量数据集
        门店生产 -> 门店生产: 计算剩余量 = 最近一次生产量 - 从生产时间到高峰期开始时间前一小时的半成品使用量
        门店生产 -> IOT或商品中心: 根据半成品编码查询半成本详细信息（半成品制备规格、单位）
        IOT或商品中心 --> 门店生产: 返回半成本详细信息
        门店生产 -> 门店生产: 计算推荐制备量 推荐制备量（按份数向上取整）=预测用量-理论剩余量
        门店生产 -> 门店生产: 加入到推荐制备数据集
        end
		门店生产 -> 门店生产: 组装推送消息
		门店生产 -> 门店生产: 组装推送消息对应的生产计划明细（时间轴明细）
		门店生产 -> 门店生产: 推送消息、生产计划明细数据持久化(事物)
        门店生产 -> 设备中心: 推送店铺高峰期提醒 以待前端取用
		门店生产 -> 设备中心: 推送高峰期生产计划明细（时间轴明细）
end
@enduml